-- migration_history
DROP TABLE IF EXISTS `migration_history`;
CREATE TABLE migration_history (
  id bigint(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '缺省字段,物理主键',
  version TEXT NOT NULL ,
  created_ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '缺省字段,创建时间'
);

-- system_setting
DROP TABLE IF EXISTS `system_setting`;
CREATE TABLE system_setting (
  `name` VARCHAR(64) NOT NULL PRIMARY KEY COMMENT '命名',
  value TEXT NOT NULL,
  description TEXT NOT NULL
);

-- user
DROP TABLE IF EXISTS `user`;
CREATE TABLE user (
  id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '缺省字段,物理主键',
  created_ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '缺省字段,创建时间',
  updated_ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  row_status VARCHAR(16) NOT NULL DEFAULT 'NORMAL'  COMMENT 'NORMA ARCHIVED',
  username VARCHAR(64) NOT NULL ,
  role VARCHAR(16) NOT NULL DEFAULT 'USER'  COMMENT 'HOST ADMIN USER',
  email VARCHAR(128) NOT NULL DEFAULT '',
  nickname VARCHAR(128) NOT NULL DEFAULT '',
  password_hash VARCHAR(128) NOT NULL DEFAULT '',
  open_id VARCHAR(128) NOT NULL DEFAULT '',
  avatar_url VARCHAR(1024) NOT NULL DEFAULT '',
  UNIQUE KEY `uk_username` (`username`) USING BTREE,
  UNIQUE KEY `uk_open_id` (`open_id`) USING BTREE
);

-- user_setting
DROP TABLE IF EXISTS `user_setting`;
CREATE TABLE user_setting (
  user_id  BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键' ,
  set_key TEXT NOT NULL,
  value TEXT NOT NULL
);

-- memo
DROP TABLE IF EXISTS `memo`;
CREATE TABLE memo (
  id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键' ,
  creator_id INTEGER NOT NULL,
  created_ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '缺省字段,创建时间',
  updated_ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  row_status VARCHAR(16) NOT NULL DEFAULT 'NORMAL'  COMMENT 'NORMAL ARCHIVED',
  content TEXT NOT NULL ,
  visibility VARCHAR(16) NOT NULL DEFAULT 'PRIVATE'  COMMENT 'PUBLIC PROTECTED PRIVATE'
);

-- memo_organizer
DROP TABLE IF EXISTS `memo_organizer`;
CREATE TABLE memo_organizer (
  memo_id BIGINT(20) UNSIGNED NOT NULL,
  user_id BIGINT(20) UNSIGNED NOT NULL,
  pinned INTEGER NOT NULL DEFAULT 0 COMMENT '0  1',
  UNIQUE KEY `uk_memo_user_id` (`memo_id`,`user_id`) USING BTREE
);

-- shortcut
DROP TABLE IF EXISTS `shortcut`;
CREATE TABLE shortcut (
  id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键' ,
  creator_id BIGINT(20) UNSIGNED NOT NULL,
  created_ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '缺省字段,创建时间',
  updated_ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  row_status VARCHAR(16) NOT NULL DEFAULT 'NORMAL'  COMMENT 'NORMAL ARCHIVED',
  title TEXT NOT NULL ,
  payload TEXT NOT NULL
);

-- resource
DROP TABLE IF EXISTS `resource`;
CREATE TABLE resource (
  id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键' ,
  creator_id BIGINT(20) UNSIGNED NOT NULL,
  created_ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '缺省字段,创建时间',
  updated_ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  filename TEXT NOT NULL ,
  filecontent BLOB DEFAULT NULL,
  external_link TEXT NOT NULL ,
  type TEXT NOT NULL ,
  size INTEGER NOT NULL DEFAULT 0,
  internal_path TEXT NOT NULL
);

-- memo_resource
DROP TABLE IF EXISTS `memo_resource`;
CREATE TABLE memo_resource (
  memo_id BIGINT(20) UNSIGNED NOT NULL,
  resource_id BIGINT(20) UNSIGNED NOT NULL,
  created_ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '缺省字段,创建时间',
  updated_ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY `uk_memo_resource_id` (`memo_id`,`resource_id`) USING BTREE
);

-- tag
DROP TABLE IF EXISTS `tag`;
CREATE TABLE tag (
  name VARCHAR(128) NOT NULL DEFAULT '',
  creator_id BIGINT(20) UNSIGNED NOT NULL,
  UNIQUE KEY `uk_name_creator_id` (`name`,`creator_id`) USING BTREE
);

-- activity
DROP TABLE IF EXISTS `activity`;
CREATE TABLE activity (
  id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键' ,
  creator_id BIGINT(20) UNSIGNED NOT NULL,
  created_ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '缺省字段,创建时间',
  type TEXT NOT NULL ,
  level VARCHAR(16) NOT NULL DEFAULT 'INFO'  COMMENT 'INFO WARN ERROR',
  payload TEXT NOT NULL
);

-- storage
DROP TABLE IF EXISTS `storage`;
CREATE TABLE storage (
  id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键' ,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  config TEXT NOT NULL
);

-- idp
DROP TABLE IF EXISTS `idp`;
CREATE TABLE idp (
  id BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键' ,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  identifier_filter TEXT NOT NULL ,
  config TEXT NOT NULL
);

-- memo_relation
DROP TABLE IF EXISTS `memo_relation`;
CREATE TABLE memo_relation (
  memo_id BIGINT(20) UNSIGNED NOT NULL,
  related_memo_id BIGINT(20) UNSIGNED NOT NULL,
  type TEXT NOT NULL,
  UNIQUE KEY `uk_memo_related_memo_id` (`memo_id`,`related_memo_id`) USING BTREE
);